 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'clientName' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'productId' : [] | [ProductId],
  'email' : string,
  'appointmentType' : AppointmentType,
  'updatedAt' : Time,
  'preferredDate' : Time,
  'notes' : string,
  'phone' : string,
}
export type AppointmentId = bigint;
export type AppointmentStatus = { 'cancelled' : null } |
  { 'pending' : null } |
  { 'completed' : null } |
  { 'confirmed' : null };
export type AppointmentType = { 'video' : null } |
  { 'inPerson' : null };
export interface CartItem {
  'id' : bigint,
  'weight' : number,
  'productId' : ProductId,
  'customizations' : string,
  'metalType' : MetalType,
  'quantity' : bigint,
}
export interface Client {
  'id' : ClientId,
  'name' : string,
  'createdAt' : Time,
  'purchaseHistory' : Array<OrderId>,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export type ClientId = bigint;
export type ExternalBlob = Uint8Array;
export interface GoldRates {
  'lastUpdated' : Time,
  'rate18K' : bigint,
  'rate22K' : bigint,
  'rate24K' : bigint,
}
export type MetalType = { 'gold18K' : null } |
  { 'gold22K' : null } |
  { 'gold24K' : null };
export interface Order {
  'id' : OrderId,
  'customerName' : string,
  'status' : OrderStatus,
  'giftWrapping' : boolean,
  'paymentStatus' : string,
  'engravingText' : string,
  'createdAt' : Time,
  'createdBy' : Principal,
  'email' : string,
  'updatedAt' : Time,
  'address' : string,
  'phone' : string,
  'items' : Array<CartItem>,
  'totalPrice' : [] | [PriceBreakdown],
}
export type OrderId = bigint;
export type OrderStatus = { 'shipped' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null } |
  { 'processing' : null };
export interface PriceBreakdown {
  'gst' : bigint,
  'weight' : number,
  'finalPrice' : bigint,
  'goldRate' : bigint,
  'metalType' : MetalType,
  'makingCharges' : bigint,
  'basePrice' : bigint,
}
export interface Product {
  'id' : ProductId,
  'diamondClarity' : [] | [string],
  'weightMax' : number,
  'weightMin' : number,
  'stockQuantity' : bigint,
  'collection' : ProductCollection,
  'limitedEdition' : boolean,
  'name' : string,
  'createdAt' : Time,
  'description' : string,
  'updatedAt' : Time,
  'diamondCarat' : [] | [number],
  'metalOptions' : Array<MetalType>,
  'diamondColor' : [] | [string],
  'goldCertification' : string,
  'giaCertification' : string,
  'basePrice' : bigint,
  'diamondCut' : [] | [string],
  'images' : Array<ExternalBlob>,
}
export type ProductCollection = { 'templeGrandeur' : null } |
  { 'diamondCouture' : null } |
  { 'limitedEditions' : null } |
  { 'royalBridal' : null };
export type ProductId = bigint;
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfile { 'name' : string, 'email' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculatePrice' : ActorMethod<
    [ProductId, MetalType, number, bigint, bigint],
    [] | [PriceBreakdown]
  >,
  'cancelAppointment' : ActorMethod<[AppointmentId], undefined>,
  'createAppointment' : ActorMethod<[Appointment], AppointmentId>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createOrder' : ActorMethod<[Order], OrderId>,
  'createProduct' : ActorMethod<[Product], ProductId>,
  'deleteProduct' : ActorMethod<[ProductId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClientById' : ActorMethod<[ClientId], [] | [Client]>,
  'getCraftsmanshipStory' : ActorMethod<[], string>,
  'getEthicalSourcingInfo' : ActorMethod<[], string>,
  'getGoldRates' : ActorMethod<[], [] | [GoldRates]>,
  'getOrderById' : ActorMethod<[OrderId], [] | [Order]>,
  'getProductById' : ActorMethod<[ProductId], [] | [Product]>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'listAppointments' : ActorMethod<
    [[] | [AppointmentStatus]],
    Array<Appointment>
  >,
  'listClients' : ActorMethod<[], Array<Client>>,
  'listOrders' : ActorMethod<[[] | [OrderStatus]], Array<Order>>,
  'listProducts' : ActorMethod<[[] | [ProductCollection]], Array<Product>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'toggleLimitedEdition' : ActorMethod<[ProductId], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateAppointmentStatus' : ActorMethod<
    [AppointmentId, AppointmentStatus],
    undefined
  >,
  'updateCraftsmanshipStory' : ActorMethod<[string], undefined>,
  'updateEthicalSourcingInfo' : ActorMethod<[string], undefined>,
  'updateGoldRates' : ActorMethod<[GoldRates], undefined>,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], undefined>,
  'updateProduct' : ActorMethod<[Product], undefined>,
  'updateProductStock' : ActorMethod<[ProductId, bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];