 

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ProductId = IDL.Nat;
export const MetalType = IDL.Variant({
  'gold18K' : IDL.Null,
  'gold22K' : IDL.Null,
  'gold24K' : IDL.Null,
});
export const PriceBreakdown = IDL.Record({
  'gst' : IDL.Nat,
  'weight' : IDL.Float64,
  'finalPrice' : IDL.Nat,
  'goldRate' : IDL.Nat,
  'metalType' : MetalType,
  'makingCharges' : IDL.Nat,
  'basePrice' : IDL.Nat,
});
export const AppointmentId = IDL.Nat;
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const AppointmentType = IDL.Variant({
  'video' : IDL.Null,
  'inPerson' : IDL.Null,
});
export const Appointment = IDL.Record({
  'id' : AppointmentId,
  'status' : AppointmentStatus,
  'clientName' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'productId' : IDL.Opt(ProductId),
  'email' : IDL.Text,
  'appointmentType' : AppointmentType,
  'updatedAt' : Time,
  'preferredDate' : Time,
  'notes' : IDL.Text,
  'phone' : IDL.Text,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
  'processing' : IDL.Null,
});
export const CartItem = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Float64,
  'productId' : ProductId,
  'customizations' : IDL.Text,
  'metalType' : MetalType,
  'quantity' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : OrderId,
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'giftWrapping' : IDL.Bool,
  'paymentStatus' : IDL.Text,
  'engravingText' : IDL.Text,
  'createdAt' : Time,
  'createdBy' : IDL.Principal,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'address' : IDL.Text,
  'phone' : IDL.Text,
  'items' : IDL.Vec(CartItem),
  'totalPrice' : IDL.Opt(PriceBreakdown),
});
export const ProductCollection = IDL.Variant({
  'templeGrandeur' : IDL.Null,
  'diamondCouture' : IDL.Null,
  'limitedEditions' : IDL.Null,
  'royalBridal' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Product = IDL.Record({
  'id' : ProductId,
  'diamondClarity' : IDL.Opt(IDL.Text),
  'weightMax' : IDL.Float64,
  'weightMin' : IDL.Float64,
  'stockQuantity' : IDL.Nat,
  'collection' : ProductCollection,
  'limitedEdition' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
  'diamondCarat' : IDL.Opt(IDL.Float64),
  'metalOptions' : IDL.Vec(MetalType),
  'diamondColor' : IDL.Opt(IDL.Text),
  'goldCertification' : IDL.Text,
  'giaCertification' : IDL.Text,
  'basePrice' : IDL.Nat,
  'diamondCut' : IDL.Opt(IDL.Text),
  'images' : IDL.Vec(ExternalBlob),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
});
export const ClientId = IDL.Nat;
export const Client = IDL.Record({
  'id' : ClientId,
  'name' : IDL.Text,
  'createdAt' : Time,
  'purchaseHistory' : IDL.Vec(OrderId),
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const GoldRates = IDL.Record({
  'lastUpdated' : Time,
  'rate18K' : IDL.Nat,
  'rate22K' : IDL.Nat,
  'rate24K' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'calculatePrice' : IDL.Func(
      [ProductId, MetalType, IDL.Float64, IDL.Nat, IDL.Nat],
      [IDL.Opt(PriceBreakdown)],
      ['query'],
    ),
  'cancelAppointment' : IDL.Func([AppointmentId], [], []),
  'createAppointment' : IDL.Func([Appointment], [AppointmentId], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createOrder' : IDL.Func([Order], [OrderId], []),
  'createProduct' : IDL.Func([Product], [ProductId], []),
  'deleteProduct' : IDL.Func([ProductId], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClientById' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
  'getCraftsmanshipStory' : IDL.Func([], [IDL.Text], ['query']),
  'getEthicalSourcingInfo' : IDL.Func([], [IDL.Text], ['query']),
  'getGoldRates' : IDL.Func([], [IDL.Opt(GoldRates)], ['query']),
  'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'listAppointments' : IDL.Func(
      [IDL.Opt(AppointmentStatus)],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'listOrders' : IDL.Func([IDL.Opt(OrderStatus)], [IDL.Vec(Order)], ['query']),
  'listProducts' : IDL.Func(
      [IDL.Opt(ProductCollection)],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'toggleLimitedEdition' : IDL.Func([ProductId], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateAppointmentStatus' : IDL.Func(
      [AppointmentId, AppointmentStatus],
      [],
      [],
    ),
  'updateCraftsmanshipStory' : IDL.Func([IDL.Text], [], []),
  'updateEthicalSourcingInfo' : IDL.Func([IDL.Text], [], []),
  'updateGoldRates' : IDL.Func([GoldRates], [], []),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
  'updateProduct' : IDL.Func([Product], [], []),
  'updateProductStock' : IDL.Func([ProductId, IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ProductId = IDL.Nat;
  const MetalType = IDL.Variant({
    'gold18K' : IDL.Null,
    'gold22K' : IDL.Null,
    'gold24K' : IDL.Null,
  });
  const PriceBreakdown = IDL.Record({
    'gst' : IDL.Nat,
    'weight' : IDL.Float64,
    'finalPrice' : IDL.Nat,
    'goldRate' : IDL.Nat,
    'metalType' : MetalType,
    'makingCharges' : IDL.Nat,
    'basePrice' : IDL.Nat,
  });
  const AppointmentId = IDL.Nat;
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const AppointmentType = IDL.Variant({
    'video' : IDL.Null,
    'inPerson' : IDL.Null,
  });
  const Appointment = IDL.Record({
    'id' : AppointmentId,
    'status' : AppointmentStatus,
    'clientName' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'productId' : IDL.Opt(ProductId),
    'email' : IDL.Text,
    'appointmentType' : AppointmentType,
    'updatedAt' : Time,
    'preferredDate' : Time,
    'notes' : IDL.Text,
    'phone' : IDL.Text,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
    'processing' : IDL.Null,
  });
  const CartItem = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Float64,
    'productId' : ProductId,
    'customizations' : IDL.Text,
    'metalType' : MetalType,
    'quantity' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : OrderId,
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'giftWrapping' : IDL.Bool,
    'paymentStatus' : IDL.Text,
    'engravingText' : IDL.Text,
    'createdAt' : Time,
    'createdBy' : IDL.Principal,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'address' : IDL.Text,
    'phone' : IDL.Text,
    'items' : IDL.Vec(CartItem),
    'totalPrice' : IDL.Opt(PriceBreakdown),
  });
  const ProductCollection = IDL.Variant({
    'templeGrandeur' : IDL.Null,
    'diamondCouture' : IDL.Null,
    'limitedEditions' : IDL.Null,
    'royalBridal' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Product = IDL.Record({
    'id' : ProductId,
    'diamondClarity' : IDL.Opt(IDL.Text),
    'weightMax' : IDL.Float64,
    'weightMin' : IDL.Float64,
    'stockQuantity' : IDL.Nat,
    'collection' : ProductCollection,
    'limitedEdition' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
    'diamondCarat' : IDL.Opt(IDL.Float64),
    'metalOptions' : IDL.Vec(MetalType),
    'diamondColor' : IDL.Opt(IDL.Text),
    'goldCertification' : IDL.Text,
    'giaCertification' : IDL.Text,
    'basePrice' : IDL.Nat,
    'diamondCut' : IDL.Opt(IDL.Text),
    'images' : IDL.Vec(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'email' : IDL.Text });
  const ClientId = IDL.Nat;
  const Client = IDL.Record({
    'id' : ClientId,
    'name' : IDL.Text,
    'createdAt' : Time,
    'purchaseHistory' : IDL.Vec(OrderId),
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const GoldRates = IDL.Record({
    'lastUpdated' : Time,
    'rate18K' : IDL.Nat,
    'rate22K' : IDL.Nat,
    'rate24K' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'calculatePrice' : IDL.Func(
        [ProductId, MetalType, IDL.Float64, IDL.Nat, IDL.Nat],
        [IDL.Opt(PriceBreakdown)],
        ['query'],
      ),
    'cancelAppointment' : IDL.Func([AppointmentId], [], []),
    'createAppointment' : IDL.Func([Appointment], [AppointmentId], []),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createOrder' : IDL.Func([Order], [OrderId], []),
    'createProduct' : IDL.Func([Product], [ProductId], []),
    'deleteProduct' : IDL.Func([ProductId], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClientById' : IDL.Func([ClientId], [IDL.Opt(Client)], ['query']),
    'getCraftsmanshipStory' : IDL.Func([], [IDL.Text], ['query']),
    'getEthicalSourcingInfo' : IDL.Func([], [IDL.Text], ['query']),
    'getGoldRates' : IDL.Func([], [IDL.Opt(GoldRates)], ['query']),
    'getOrderById' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProductById' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'listAppointments' : IDL.Func(
        [IDL.Opt(AppointmentStatus)],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'listClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'listOrders' : IDL.Func(
        [IDL.Opt(OrderStatus)],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'listProducts' : IDL.Func(
        [IDL.Opt(ProductCollection)],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'toggleLimitedEdition' : IDL.Func([ProductId], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateAppointmentStatus' : IDL.Func(
        [AppointmentId, AppointmentStatus],
        [],
        [],
      ),
    'updateCraftsmanshipStory' : IDL.Func([IDL.Text], [], []),
    'updateEthicalSourcingInfo' : IDL.Func([IDL.Text], [], []),
    'updateGoldRates' : IDL.Func([GoldRates], [], []),
    'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [], []),
    'updateProduct' : IDL.Func([Product], [], []),
    'updateProductStock' : IDL.Func([ProductId, IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };