/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface UserProfile {
    name: string;
    email: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export type AppointmentId = bigint;
export interface GoldRates {
    lastUpdated: Time;
    rate18K: bigint;
    rate22K: bigint;
    rate24K: bigint;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PriceBreakdown {
    gst: bigint;
    weight: number;
    finalPrice: bigint;
    goldRate: bigint;
    metalType: MetalType;
    makingCharges: bigint;
    basePrice: bigint;
}
export type StripeSessionStatus = {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
};
export interface Client {
    id: ClientId;
    name: string;
    createdAt: Time;
    purchaseHistory: Array<OrderId>;
    email: string;
    address: string;
    phone: string;
}
export interface StripeConfiguration {
    allowedCountries: Array<string>;
    secretKey: string;
}
export type ClientId = bigint;
export interface Order {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    giftWrapping: boolean;
    paymentStatus: string;
    engravingText: string;
    createdAt: Time;
    createdBy: Principal;
    email: string;
    updatedAt: Time;
    address: string;
    phone: string;
    items: Array<CartItem>;
    totalPrice?: PriceBreakdown;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface ShoppingItem {
    productName: string;
    currency: string;
    quantity: bigint;
    priceInCents: bigint;
    productDescription: string;
}
export interface CartItem {
    id: bigint;
    weight: number;
    productId: ProductId;
    customizations: string;
    metalType: MetalType;
    quantity: bigint;
}
export type ProductId = bigint;
export interface Appointment {
    id: AppointmentId;
    status: AppointmentStatus;
    clientName: string;
    createdAt: Time;
    createdBy: Principal;
    productId?: ProductId;
    email: string;
    appointmentType: AppointmentType;
    updatedAt: Time;
    preferredDate: Time;
    notes: string;
    phone: string;
}
export interface Product {
    id: ProductId;
    diamondClarity?: string;
    weightMax: number;
    weightMin: number;
    stockQuantity: bigint;
    collection: ProductCollection;
    limitedEdition: boolean;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    diamondCarat?: number;
    metalOptions: Array<MetalType>;
    diamondColor?: string;
    goldCertification: string;
    giaCertification: string;
    basePrice: bigint;
    diamondCut?: string;
    images: Array<ExternalBlob>;
}
export type OrderId = bigint;
export enum AppointmentStatus {
    cancelled = "cancelled",
    pending = "pending",
    completed = "completed",
    confirmed = "confirmed"
}
export enum AppointmentType {
    video = "video",
    inPerson = "inPerson"
}
export enum MetalType {
    gold18K = "gold18K",
    gold22K = "gold22K",
    gold24K = "gold24K"
}
export enum OrderStatus {
    shipped = "shipped",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed",
    processing = "processing"
}
export enum ProductCollection {
    templeGrandeur = "templeGrandeur",
    diamondCouture = "diamondCouture",
    limitedEditions = "limitedEditions",
    royalBridal = "royalBridal"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    calculatePrice(productId: ProductId, metalType: MetalType, weight: number, makingCharges: bigint, gst: bigint): Promise<PriceBreakdown | null>;
    cancelAppointment(id: AppointmentId): Promise<void>;
    createAppointment(appointment: Appointment): Promise<AppointmentId>;
    createCheckoutSession(items: Array<ShoppingItem>, successUrl: string, cancelUrl: string): Promise<string>;
    createOrder(order: Order): Promise<OrderId>;
    createProduct(product: Product): Promise<ProductId>;
    deleteProduct(id: ProductId): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClientById(id: ClientId): Promise<Client | null>;
    getCraftsmanshipStory(): Promise<string>;
    getEthicalSourcingInfo(): Promise<string>;
    getGoldRates(): Promise<GoldRates | null>;
    getOrderById(id: OrderId): Promise<Order | null>;
    getProductById(id: ProductId): Promise<Product | null>;
    getStripeSessionStatus(sessionId: string): Promise<StripeSessionStatus>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    isStripeConfigured(): Promise<boolean>;
    listAppointments(status: AppointmentStatus | null): Promise<Array<Appointment>>;
    listClients(): Promise<Array<Client>>;
    listOrders(status: OrderStatus | null): Promise<Array<Order>>;
    listProducts(collection: ProductCollection | null): Promise<Array<Product>>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    setStripeConfiguration(config: StripeConfiguration): Promise<void>;
    toggleLimitedEdition(productId: ProductId): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updateAppointmentStatus(id: AppointmentId, status: AppointmentStatus): Promise<void>;
    updateCraftsmanshipStory(story: string): Promise<void>;
    updateEthicalSourcingInfo(info: string): Promise<void>;
    updateGoldRates(newRates: GoldRates): Promise<void>;
    updateOrderStatus(id: OrderId, status: OrderStatus): Promise<void>;
    updateProduct(updatedProduct: Product): Promise<void>;
    updateProductStock(productId: ProductId, quantity: bigint): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentId as _AppointmentId, AppointmentStatus as _AppointmentStatus, AppointmentType as _AppointmentType, CartItem as _CartItem, Client as _Client, ExternalBlob as _ExternalBlob, GoldRates as _GoldRates, MetalType as _MetalType, Order as _Order, OrderId as _OrderId, OrderStatus as _OrderStatus, PriceBreakdown as _PriceBreakdown, Product as _Product, ProductCollection as _ProductCollection, ProductId as _ProductId, StripeSessionStatus as _StripeSessionStatus, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async calculatePrice(arg0: ProductId, arg1: MetalType, arg2: number, arg3: bigint, arg4: bigint): Promise<PriceBreakdown | null> {
        if (this.processError) {
            try {
                const result = await this.actor.calculatePrice(arg0, to_candid_MetalType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.calculatePrice(arg0, to_candid_MetalType_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async cancelAppointment(arg0: AppointmentId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async createAppointment(arg0: Appointment): Promise<AppointmentId> {
        if (this.processError) {
            try {
                const result = await this.actor.createAppointment(to_candid_Appointment_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createAppointment(to_candid_Appointment_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createCheckoutSession(arg0: Array<ShoppingItem>, arg1: string, arg2: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCheckoutSession(arg0, arg1, arg2);
            return result;
        }
    }
    async createOrder(arg0: Order): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(to_candid_Order_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(to_candid_Order_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async createProduct(arg0: Product): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(await to_candid_Product_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(await to_candid_Product_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClientById(arg0: ClientId): Promise<Client | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getClientById(arg0);
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClientById(arg0);
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCraftsmanshipStory(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getCraftsmanshipStory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCraftsmanshipStory();
            return result;
        }
    }
    async getEthicalSourcingInfo(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getEthicalSourcingInfo();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEthicalSourcingInfo();
            return result;
        }
    }
    async getGoldRates(): Promise<GoldRates | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGoldRates();
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGoldRates();
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderById(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderById(arg0);
                return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderById(arg0);
            return from_candid_opt_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStripeSessionStatus(arg0: string): Promise<StripeSessionStatus> {
        if (this.processError) {
            try {
                const result = await this.actor.getStripeSessionStatus(arg0);
                return from_candid_StripeSessionStatus_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStripeSessionStatus(arg0);
            return from_candid_StripeSessionStatus_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isStripeConfigured(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isStripeConfigured();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isStripeConfigured();
            return result;
        }
    }
    async listAppointments(arg0: AppointmentStatus | null): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAppointments(to_candid_opt_n65(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAppointments(to_candid_opt_n65(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async listClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.listClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listClients();
            return result;
        }
    }
    async listOrders(arg0: OrderStatus | null): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listOrders(to_candid_opt_n74(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listOrders(to_candid_opt_n74(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n75(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(arg0: ProductCollection | null): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts(to_candid_opt_n76(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts(to_candid_opt_n76(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n77(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setStripeConfiguration(arg0: StripeConfiguration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setStripeConfiguration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setStripeConfiguration(arg0);
            return result;
        }
    }
    async toggleLimitedEdition(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleLimitedEdition(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleLimitedEdition(arg0);
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updateAppointmentStatus(arg0: AppointmentId, arg1: AppointmentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n19(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAppointmentStatus(arg0, to_candid_AppointmentStatus_n19(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateCraftsmanshipStory(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCraftsmanshipStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCraftsmanshipStory(arg0);
            return result;
        }
    }
    async updateEthicalSourcingInfo(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEthicalSourcingInfo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEthicalSourcingInfo(arg0);
            return result;
        }
    }
    async updateGoldRates(arg0: GoldRates): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGoldRates(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGoldRates(arg0);
            return result;
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n25(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n25(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProduct(arg0: Product): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(await to_candid_Product_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(await to_candid_Product_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProductStock(arg0: ProductId, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProductStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProductStock(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n70(_uploadFile, _downloadFile, value);
}
function from_candid_AppointmentType_n72(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentType): AppointmentType {
    return from_candid_variant_n73(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n68(_uploadFile, _downloadFile, value);
}
function from_candid_CartItem_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_MetalType_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MetalType): MetalType {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_PriceBreakdown_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PriceBreakdown): PriceBreakdown {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_ProductCollection_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProductCollection): ProductCollection {
    return from_candid_variant_n57(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_StripeSessionStatus_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StripeSessionStatus): StripeSessionStatus {
    return from_candid_variant_n63(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PriceBreakdown]): PriceBreakdown | null {
    return value.length === 0 ? null : from_candid_PriceBreakdown_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Client]): Client | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GoldRates]): GoldRates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n45(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Promise<Product | null> {
    return value.length === 0 ? null : await from_candid_Product_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n71(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProductId]): ProductId | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gst: bigint;
    weight: number;
    finalPrice: bigint;
    goldRate: bigint;
    metalType: _MetalType;
    makingCharges: bigint;
    basePrice: bigint;
}): {
    gst: bigint;
    weight: number;
    finalPrice: bigint;
    goldRate: bigint;
    metalType: MetalType;
    makingCharges: bigint;
    basePrice: bigint;
} {
    return {
        gst: value.gst,
        weight: value.weight,
        finalPrice: value.finalPrice,
        goldRate: value.goldRate,
        metalType: from_candid_MetalType_n15(_uploadFile, _downloadFile, value.metalType),
        makingCharges: value.makingCharges,
        basePrice: value.basePrice
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    giftWrapping: boolean;
    paymentStatus: string;
    engravingText: string;
    createdAt: _Time;
    createdBy: Principal;
    email: string;
    updatedAt: _Time;
    address: string;
    phone: string;
    items: Array<_CartItem>;
    totalPrice: [] | [_PriceBreakdown];
}): {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    giftWrapping: boolean;
    paymentStatus: string;
    engravingText: string;
    createdAt: Time;
    createdBy: Principal;
    email: string;
    updatedAt: Time;
    address: string;
    phone: string;
    items: Array<CartItem>;
    totalPrice?: PriceBreakdown;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_OrderStatus_n47(_uploadFile, _downloadFile, value.status),
        giftWrapping: value.giftWrapping,
        paymentStatus: value.paymentStatus,
        engravingText: value.engravingText,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        updatedAt: value.updatedAt,
        address: value.address,
        phone: value.phone,
        items: from_candid_vec_n49(_uploadFile, _downloadFile, value.items),
        totalPrice: record_opt_to_undefined(from_candid_opt_n12(_uploadFile, _downloadFile, value.totalPrice))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: number;
    productId: _ProductId;
    customizations: string;
    metalType: _MetalType;
    quantity: bigint;
}): {
    id: bigint;
    weight: number;
    productId: ProductId;
    customizations: string;
    metalType: MetalType;
    quantity: bigint;
} {
    return {
        id: value.id,
        weight: value.weight,
        productId: value.productId,
        customizations: value.customizations,
        metalType: from_candid_MetalType_n15(_uploadFile, _downloadFile, value.metalType),
        quantity: value.quantity
    };
}
async function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    diamondClarity: [] | [string];
    weightMax: number;
    weightMin: number;
    stockQuantity: bigint;
    collection: _ProductCollection;
    limitedEdition: boolean;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    diamondCarat: [] | [number];
    metalOptions: Array<_MetalType>;
    diamondColor: [] | [string];
    goldCertification: string;
    giaCertification: string;
    basePrice: bigint;
    diamondCut: [] | [string];
    images: Array<_ExternalBlob>;
}): Promise<{
    id: ProductId;
    diamondClarity?: string;
    weightMax: number;
    weightMin: number;
    stockQuantity: bigint;
    collection: ProductCollection;
    limitedEdition: boolean;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    diamondCarat?: number;
    metalOptions: Array<MetalType>;
    diamondColor?: string;
    goldCertification: string;
    giaCertification: string;
    basePrice: bigint;
    diamondCut?: string;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        diamondClarity: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.diamondClarity)),
        weightMax: value.weightMax,
        weightMin: value.weightMin,
        stockQuantity: value.stockQuantity,
        collection: from_candid_ProductCollection_n56(_uploadFile, _downloadFile, value.collection),
        limitedEdition: value.limitedEdition,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        diamondCarat: record_opt_to_undefined(from_candid_opt_n58(_uploadFile, _downloadFile, value.diamondCarat)),
        metalOptions: from_candid_vec_n59(_uploadFile, _downloadFile, value.metalOptions),
        diamondColor: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.diamondColor)),
        goldCertification: value.goldCertification,
        giaCertification: value.giaCertification,
        basePrice: value.basePrice,
        diamondCut: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.diamondCut)),
        images: await from_candid_vec_n60(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    userPrincipal: [] | [string];
    response: string;
}): {
    userPrincipal?: string;
    response: string;
} {
    return {
        userPrincipal: record_opt_to_undefined(from_candid_opt_n55(_uploadFile, _downloadFile, value.userPrincipal)),
        response: value.response
    };
}
function from_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _AppointmentId;
    status: _AppointmentStatus;
    clientName: string;
    createdAt: _Time;
    createdBy: Principal;
    productId: [] | [_ProductId];
    email: string;
    appointmentType: _AppointmentType;
    updatedAt: _Time;
    preferredDate: _Time;
    notes: string;
    phone: string;
}): {
    id: AppointmentId;
    status: AppointmentStatus;
    clientName: string;
    createdAt: Time;
    createdBy: Principal;
    productId?: ProductId;
    email: string;
    appointmentType: AppointmentType;
    updatedAt: Time;
    preferredDate: Time;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n69(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        productId: record_opt_to_undefined(from_candid_opt_n71(_uploadFile, _downloadFile, value.productId)),
        email: value.email,
        appointmentType: from_candid_AppointmentType_n72(_uploadFile, _downloadFile, value.appointmentType),
        updatedAt: value.updatedAt,
        preferredDate: value.preferredDate,
        notes: value.notes,
        phone: value.phone
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gold18K: null;
} | {
    gold22K: null;
} | {
    gold24K: null;
}): MetalType {
    return "gold18K" in value ? MetalType.gold18K : "gold22K" in value ? MetalType.gold22K : "gold24K" in value ? MetalType.gold24K : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    processing: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : "processing" in value ? OrderStatus.processing : value;
}
function from_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    templeGrandeur: null;
} | {
    diamondCouture: null;
} | {
    limitedEditions: null;
} | {
    royalBridal: null;
}): ProductCollection {
    return "templeGrandeur" in value ? ProductCollection.templeGrandeur : "diamondCouture" in value ? ProductCollection.diamondCouture : "limitedEditions" in value ? ProductCollection.limitedEditions : "royalBridal" in value ? ProductCollection.royalBridal : value;
}
function from_candid_variant_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    completed: {
        userPrincipal: [] | [string];
        response: string;
    };
} | {
    failed: {
        error: string;
    };
}): {
    __kind__: "completed";
    completed: {
        userPrincipal?: string;
        response: string;
    };
} | {
    __kind__: "failed";
    failed: {
        error: string;
    };
} {
    return "completed" in value ? {
        __kind__: "completed",
        completed: from_candid_record_n64(_uploadFile, _downloadFile, value.completed)
    } : "failed" in value ? {
        __kind__: "failed",
        failed: value.failed
    } : value;
}
function from_candid_variant_n70(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "pending" in value ? AppointmentStatus.pending : "completed" in value ? AppointmentStatus.completed : "confirmed" in value ? AppointmentStatus.confirmed : value;
}
function from_candid_variant_n73(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    inPerson: null;
}): AppointmentType {
    return "video" in value ? AppointmentType.video : "inPerson" in value ? AppointmentType.inPerson : value;
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MetalType>): Array<MetalType> {
    return value.map((x)=>from_candid_MetalType_n15(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n61(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n67(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n75(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n45(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n77(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n53(_uploadFile, _downloadFile, x)));
}
function to_candid_AppointmentStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): _AppointmentStatus {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_AppointmentType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentType): _AppointmentType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_Appointment_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Appointment): _Appointment {
    return to_candid_record_n18(_uploadFile, _downloadFile, value);
}
function to_candid_CartItem_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_MetalType_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetalType): _MetalType {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function to_candid_Order_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Order): _Order {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_PriceBreakdown_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PriceBreakdown): _PriceBreakdown {
    return to_candid_record_n31(_uploadFile, _downloadFile, value);
}
function to_candid_ProductCollection_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCollection): _ProductCollection {
    return to_candid_variant_n35(_uploadFile, _downloadFile, value);
}
async function to_candid_Product_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Product): Promise<_Product> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus | null): [] | [_AppointmentStatus] {
    return value === null ? candid_none() : candid_some(to_candid_AppointmentStatus_n19(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n74(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus | null): [] | [_OrderStatus] {
    return value === null ? candid_none() : candid_some(to_candid_OrderStatus_n25(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n76(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCollection | null): [] | [_ProductCollection] {
    return value === null ? candid_none() : candid_some(to_candid_ProductCollection_n34(_uploadFile, _downloadFile, value));
}
function to_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: AppointmentId;
    status: AppointmentStatus;
    clientName: string;
    createdAt: Time;
    createdBy: Principal;
    productId?: ProductId;
    email: string;
    appointmentType: AppointmentType;
    updatedAt: Time;
    preferredDate: Time;
    notes: string;
    phone: string;
}): {
    id: _AppointmentId;
    status: _AppointmentStatus;
    clientName: string;
    createdAt: _Time;
    createdBy: Principal;
    productId: [] | [_ProductId];
    email: string;
    appointmentType: _AppointmentType;
    updatedAt: _Time;
    preferredDate: _Time;
    notes: string;
    phone: string;
} {
    return {
        id: value.id,
        status: to_candid_AppointmentStatus_n19(_uploadFile, _downloadFile, value.status),
        clientName: value.clientName,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        productId: value.productId ? candid_some(value.productId) : candid_none(),
        email: value.email,
        appointmentType: to_candid_AppointmentType_n21(_uploadFile, _downloadFile, value.appointmentType),
        updatedAt: value.updatedAt,
        preferredDate: value.preferredDate,
        notes: value.notes,
        phone: value.phone
    };
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: OrderId;
    customerName: string;
    status: OrderStatus;
    giftWrapping: boolean;
    paymentStatus: string;
    engravingText: string;
    createdAt: Time;
    createdBy: Principal;
    email: string;
    updatedAt: Time;
    address: string;
    phone: string;
    items: Array<CartItem>;
    totalPrice?: PriceBreakdown;
}): {
    id: _OrderId;
    customerName: string;
    status: _OrderStatus;
    giftWrapping: boolean;
    paymentStatus: string;
    engravingText: string;
    createdAt: _Time;
    createdBy: Principal;
    email: string;
    updatedAt: _Time;
    address: string;
    phone: string;
    items: Array<_CartItem>;
    totalPrice: [] | [_PriceBreakdown];
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: to_candid_OrderStatus_n25(_uploadFile, _downloadFile, value.status),
        giftWrapping: value.giftWrapping,
        paymentStatus: value.paymentStatus,
        engravingText: value.engravingText,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        email: value.email,
        updatedAt: value.updatedAt,
        address: value.address,
        phone: value.phone,
        items: to_candid_vec_n27(_uploadFile, _downloadFile, value.items),
        totalPrice: value.totalPrice ? candid_some(to_candid_PriceBreakdown_n30(_uploadFile, _downloadFile, value.totalPrice)) : candid_none()
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    weight: number;
    productId: ProductId;
    customizations: string;
    metalType: MetalType;
    quantity: bigint;
}): {
    id: bigint;
    weight: number;
    productId: _ProductId;
    customizations: string;
    metalType: _MetalType;
    quantity: bigint;
} {
    return {
        id: value.id,
        weight: value.weight,
        productId: value.productId,
        customizations: value.customizations,
        metalType: to_candid_MetalType_n10(_uploadFile, _downloadFile, value.metalType),
        quantity: value.quantity
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gst: bigint;
    weight: number;
    finalPrice: bigint;
    goldRate: bigint;
    metalType: MetalType;
    makingCharges: bigint;
    basePrice: bigint;
}): {
    gst: bigint;
    weight: number;
    finalPrice: bigint;
    goldRate: bigint;
    metalType: _MetalType;
    makingCharges: bigint;
    basePrice: bigint;
} {
    return {
        gst: value.gst,
        weight: value.weight,
        finalPrice: value.finalPrice,
        goldRate: value.goldRate,
        metalType: to_candid_MetalType_n10(_uploadFile, _downloadFile, value.metalType),
        makingCharges: value.makingCharges,
        basePrice: value.basePrice
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: ProductId;
    diamondClarity?: string;
    weightMax: number;
    weightMin: number;
    stockQuantity: bigint;
    collection: ProductCollection;
    limitedEdition: boolean;
    name: string;
    createdAt: Time;
    description: string;
    updatedAt: Time;
    diamondCarat?: number;
    metalOptions: Array<MetalType>;
    diamondColor?: string;
    goldCertification: string;
    giaCertification: string;
    basePrice: bigint;
    diamondCut?: string;
    images: Array<ExternalBlob>;
}): Promise<{
    id: _ProductId;
    diamondClarity: [] | [string];
    weightMax: number;
    weightMin: number;
    stockQuantity: bigint;
    collection: _ProductCollection;
    limitedEdition: boolean;
    name: string;
    createdAt: _Time;
    description: string;
    updatedAt: _Time;
    diamondCarat: [] | [number];
    metalOptions: Array<_MetalType>;
    diamondColor: [] | [string];
    goldCertification: string;
    giaCertification: string;
    basePrice: bigint;
    diamondCut: [] | [string];
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        diamondClarity: value.diamondClarity ? candid_some(value.diamondClarity) : candid_none(),
        weightMax: value.weightMax,
        weightMin: value.weightMin,
        stockQuantity: value.stockQuantity,
        collection: to_candid_ProductCollection_n34(_uploadFile, _downloadFile, value.collection),
        limitedEdition: value.limitedEdition,
        name: value.name,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        diamondCarat: value.diamondCarat ? candid_some(value.diamondCarat) : candid_none(),
        metalOptions: to_candid_vec_n36(_uploadFile, _downloadFile, value.metalOptions),
        diamondColor: value.diamondColor ? candid_some(value.diamondColor) : candid_none(),
        goldCertification: value.goldCertification,
        giaCertification: value.giaCertification,
        basePrice: value.basePrice,
        diamondCut: value.diamondCut ? candid_some(value.diamondCut) : candid_none(),
        images: await to_candid_vec_n37(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MetalType): {
    gold18K: null;
} | {
    gold22K: null;
} | {
    gold24K: null;
} {
    return value == MetalType.gold18K ? {
        gold18K: null
    } : value == MetalType.gold22K ? {
        gold22K: null
    } : value == MetalType.gold24K ? {
        gold24K: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentStatus): {
    cancelled: null;
} | {
    pending: null;
} | {
    completed: null;
} | {
    confirmed: null;
} {
    return value == AppointmentStatus.cancelled ? {
        cancelled: null
    } : value == AppointmentStatus.pending ? {
        pending: null
    } : value == AppointmentStatus.completed ? {
        completed: null
    } : value == AppointmentStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AppointmentType): {
    video: null;
} | {
    inPerson: null;
} {
    return value == AppointmentType.video ? {
        video: null
    } : value == AppointmentType.inPerson ? {
        inPerson: null
    } : value;
}
function to_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    shipped: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} | {
    processing: null;
} {
    return value == OrderStatus.shipped ? {
        shipped: null
    } : value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value == OrderStatus.processing ? {
        processing: null
    } : value;
}
function to_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductCollection): {
    templeGrandeur: null;
} | {
    diamondCouture: null;
} | {
    limitedEditions: null;
} | {
    royalBridal: null;
} {
    return value == ProductCollection.templeGrandeur ? {
        templeGrandeur: null
    } : value == ProductCollection.diamondCouture ? {
        diamondCouture: null
    } : value == ProductCollection.limitedEditions ? {
        limitedEditions: null
    } : value == ProductCollection.royalBridal ? {
        royalBridal: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n28(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<MetalType>): Array<_MetalType> {
    return value.map((x)=>to_candid_MetalType_n10(_uploadFile, _downloadFile, x));
}
async function to_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n38(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
